# Generated by Django 3.2.7 on 2022-05-17 11:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('veg', '0002_auto_20220517_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosecountry',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
        migrations.CreateModel(
            name='Vegan_Veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/veg')),
                ('discriptiion', models.TextField(blank=True, null=True)),
                ('choose_veg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veg.chooseveg')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name_plural': 'Vegan_Veg',
                'db_table': 'Vegan_Veg',
            },
        ),
    ]
