# Generated by Django 3.2.7 on 2022-05-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('veg', '0004_auto_20220517_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeveg',
            old_name='choose_veg',
            new_name='type_veg',
        ),
        migrations.CreateModel(
            name='RestrurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('vagan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veg.veganveg')),
            ],
            options={
                'verbose_name_plural': 'RestrurantInfo',
                'db_table': 'RestrurantInfo',
            },
        ),
        migrations.CreateModel(
            name='RatingReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_discriptiion', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name_plural': 'RatingReviews',
                'db_table': 'RatingReviews',
            },
        ),
        migrations.CreateModel(
            name='OrderOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('discriptiion', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order', models.ManyToManyField(to='veg.VeganVeg')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name_plural': 'OrderOnline',
                'db_table': 'OrderOnline',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.FileField(blank=True, null=True, upload_to='media/gallery')),
                ('vagan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veg.veganveg')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
                'db_table': 'Gallery',
            },
        ),
    ]
