# Generated by Django 3.2.7 on 2022-05-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('veg', '0005_auto_20220517_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VeganVeg',
            new_name='Hotel',
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hotel'},
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='Hotel',
        ),
    ]
