# Generated by Django 3.2.7 on 2022-05-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0008_ratingreviews_hotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restrurantinfo',
            old_name='vagan',
            new_name='hotal',
        ),
    ]
