# Generated by Django 3.2.7 on 2022-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0009_rename_vagan_restrurantinfo_hotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodonlineorder',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/food'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/hotal'),
        ),
    ]
