# Generated by Django 3.2.7 on 2022-05-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0011_booktable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='book_id',
            new_name='user_id',
        ),
    ]
